workspace:
  base: /go
  path: src/github.com/amarburg/go-movieset

pipeline:
  build:
    image: amarburg/golang-ffmpeg:stretch-1.10
    pull: true
    commands:
      - go get -t -v
      - go build
      - go test

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status:
        - success
        - failure
