workspace:
  base: /go
  path: src/github.com/amarburg/go-movieset

pipeline:
  build:
    image: amarburg/golang-ffmpeg:latest
    pull: true
    commands:
      - go get -t -v
      - go build
      - go test

  lint:
    image: amarburg/golang-ffmpeg:latest-ci
    pull: true
    commands:
      - echo $GOPATH
      - ls $GOPATH
      - golangci-lint run

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status:
        - success
        - failure
